/**
 * @module storageErrorCode
 * @description Runtime error code constants plus the corresponding string-literal type.
 * @since 2025-11-19
 * @version 2.0.0
 */

export const StorageErrorCode = {
  // Table error codes
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  TABLE_CREATE_FAILED: 'TABLE_CREATE_FAILED',
  TABLE_DELETE_FAILED: 'TABLE_DELETE_FAILED',
  TABLE_UPDATE_FAILED: 'TABLE_UPDATE_FAILED',
  TABLE_READ_FAILED: 'TABLE_READ_FAILED',
  TABLE_COUNT_FAILED: 'TABLE_COUNT_FAILED',
  TABLE_SIZE_FAILED: 'TABLE_SIZE_FAILED',
  TABLE_CHUNK_FAILED: 'TABLE_CHUNK_FAILED',
  TABLE_CHUNK_SIZE_FAILED: 'TABLE_CHUNK_SIZE_FAILED',
  TABLE_CHUNK_SIZE_TOO_SMALL: 'TABLE_CHUNK_SIZE_TOO_SMALL',
  TABLE_CHUNK_SIZE_TOO_LARGE: 'TABLE_CHUNK_SIZE_TOO_LARGE',
  TABLE_CHUNK_SIZE_TOO_MANY: 'TABLE_CHUNK_SIZE_TOO_MANY',
  TABLE_CHUNK_SIZE_TOO_FEW: 'TABLE_CHUNK_SIZE_TOO_FEW',
  TABLE_CHUNK_SIZE_TOO_MUCH: 'TABLE_CHUNK_SIZE_TOO_MUCH',
  TABLE_CHUNK_SIZE_TOO_LITTLE: 'TABLE_CHUNK_SIZE_TOO_LITTLE',
  TABLE_ALREADY_EXISTS: 'TABLE_ALREADY_EXISTS',
  TABLE_NAME_INVALID: 'TABLE_NAME_INVALID',
  TABLE_COLUMN_INVALID: 'TABLE_COLUMN_INVALID',
  TABLE_INDEX_INVALID: 'TABLE_INDEX_INVALID',
  TABLE_INDEX_ALREADY_EXISTS: 'TABLE_INDEX_ALREADY_EXISTS',
  TABLE_INDEX_NOT_FOUND: 'TABLE_INDEX_NOT_FOUND',
  TABLE_INDEX_NAME_INVALID: 'TABLE_INDEX_NAME_INVALID',
  TABLE_INDEX_TYPE_INVALID: 'TABLE_INDEX_TYPE_INVALID',
  TABLE_INDEX_UNIQUE_INVALID: 'TABLE_INDEX_UNIQUE_INVALID',
  TABLE_INDEX_NOT_UNIQUE: 'TABLE_INDEX_NOT_UNIQUE',
  // File error codes
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  FILE_NAME_INVALID: 'FILE_NAME_INVALID',
  FILE_CONTENT_INVALID: 'FILE_CONTENT_INVALID',
  FILE_CONTENT_TOO_LARGE: 'FILE_CONTENT_TOO_LARGE',
  FILE_CONTENT_TOO_SMALL: 'FILE_CONTENT_TOO_SMALL',
  FILE_CONTENT_TOO_LONG: 'FILE_CONTENT_TOO_LONG',
  FILE_CONTENT_TOO_SHORT: 'FILE_CONTENT_TOO_SHORT',
  FILE_CONTENT_TOO_MANY: 'FILE_CONTENT_TOO_MANY',
  FILE_CONTENT_TOO_FEW: 'FILE_CONTENT_TOO_FEW',
  FILE_READ_FAILED: 'FILE_READ_FAILED',
  FILE_WRITE_FAILED: 'FILE_WRITE_FAILED',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  FILE_MOVE_FAILED: 'FILE_MOVE_FAILED',
  FILE_COPY_FAILED: 'FILE_COPY_FAILED',
  FILE_RENAME_FAILED: 'FILE_RENAME_FAILED',
  FILE_TRUNCATE_FAILED: 'FILE_TRUNCATE_FAILED',
  FILE_CLOSE_FAILED: 'FILE_CLOSE_FAILED',
  FILE_SEEK_FAILED: 'FILE_SEEK_FAILED',
  FILE_TELL_FAILED: 'FILE_TELL_FAILED',
  // General error codes
  UNKNOWN: 'UNKNOWN',
  TIMEOUT: 'TIMEOUT',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  AUTH_ON_ACCESS_UNSUPPORTED: 'AUTH_ON_ACCESS_UNSUPPORTED',
  EXPO_MODULE_MISSING: 'EXPO_MODULE_MISSING',
  DISK_FULL: 'DISK_FULL',
  CORRUPTED_DATA: 'CORRUPTED_DATA',
  DATA_INCOMPLETE: 'DATA_INCOMPLETE',
  CHUNK_INTEGRITY_FAILED: 'CHUNK_INTEGRITY_FAILED',
  META_FILE_READ_ERROR: 'META_FILE_READ_ERROR',
  META_FILE_WRITE_ERROR: 'META_FILE_WRITE_ERROR',
  QUERY_FAILED: 'QUERY_FAILED',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  WRITTEN_COUNT_MISMATCH: 'WRITTEN_COUNT_MISMATCH',
  BULK_OPERATION_FAILED: 'BULK_OPERATION_FAILED',
  // Transaction error codes
  TRANSACTION_IN_PROGRESS: 'TRANSACTION_IN_PROGRESS',
  NO_TRANSACTION_IN_PROGRESS: 'NO_TRANSACTION_IN_PROGRESS',
  TRANSACTION_COMMIT_FAILED: 'TRANSACTION_COMMIT_FAILED',
  TRANSACTION_ROLLBACK_FAILED: 'TRANSACTION_ROLLBACK_FAILED',
  // Concurrency error codes
  LOCK_TIMEOUT: 'LOCK_TIMEOUT',
} as const;

export type StorageErrorCode = (typeof StorageErrorCode)[keyof typeof StorageErrorCode];
